// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCor6QrPnh00TVlP768qbgKMLTzS8jmzVU',
    appId: '1:1062450868837:web:1f927802499c5efa7d0c8c',
    messagingSenderId: '1062450868837',
    projectId: 'babylon-radio-app',
    authDomain: 'babylon-radio-app.firebaseapp.com',
    storageBucket: 'babylon-radio-app.firebasestorage.app',
    measurementId: 'G-TMTTQ2FW17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxuUnWXpKSdrCTarebyeEEXlQ-mkoxsBA',
    appId: '1:1062450868837:android:d25426293df164577d0c8c',
    messagingSenderId: '1062450868837',
    projectId: 'babylon-radio-app',
    storageBucket: 'babylon-radio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPM1sTHDUAW6qDkXow0BdK_D9Yphu6_U4',
    appId: '1:1062450868837:ios:ade313878227b07e7d0c8c',
    messagingSenderId: '1062450868837',
    projectId: 'babylon-radio-app',
    storageBucket: 'babylon-radio-app.firebasestorage.app',
    iosBundleId: 'com.example.babylonFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPM1sTHDUAW6qDkXow0BdK_D9Yphu6_U4',
    appId: '1:1062450868837:ios:ade313878227b07e7d0c8c',
    messagingSenderId: '1062450868837',
    projectId: 'babylon-radio-app',
    storageBucket: 'babylon-radio-app.firebasestorage.app',
    iosBundleId: 'com.example.babylonFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCor6QrPnh00TVlP768qbgKMLTzS8jmzVU',
    appId: '1:1062450868837:web:41dfd1b4e783380c7d0c8c',
    messagingSenderId: '1062450868837',
    projectId: 'babylon-radio-app',
    authDomain: 'babylon-radio-app.firebaseapp.com',
    storageBucket: 'babylon-radio-app.firebasestorage.app',
    measurementId: 'G-L7JWC2P9V1',
  );
}
